classifier:
  locus:
    count:
      keep_duplicates: false
      padding: 2
      stitch: false
    min_support: 100
    msings:
      peak_height_cutoff: 0.05
      std_dev_rate: 2.0
    sklearn:
      classifier: SVC
      classifier_params:
  model:  # learn/microsat/microsatModel.json
  random_seed: 0
  sample:
    consensus_method: ratio
    instability_threshold: 0.33
    locus_weight_is_score: false
    min_voting_loci: 4
    undetermined_weight: 0
input:
  aln_pattern:  # aln/{sample}.bam
  excluded_samples: [Undetermined]
  R1_pattern:   # raw/{sample}_R1.fastq.gz
  R2_pattern:   # raw/{sample}_R2.fastq.gz
reference:
  microsatellites:   # design/microsatellites.bed
  sequences:    # genome/hg38.fa
