classifier:
  locus:
    classifier: SVC
    classifier_params:
    min_support: 100
  model:  # learn/microsat/microsatModel.json
  random_seed: 0
  sample:
    consensus_method: ratio
    instability_threshold: 0.3
    locus_weight_is_score: false
    min_voting_loci: 3
    undetermined_weight: 0
input:
  R1_pattern:   # raw/{sample}_R1.fastq.gz
  R2_pattern:   # raw/{sample}_R2.fastq.gz
  aln_pattern:  # aln/{sample}.bam
  excluded_samples: [Undetermined]
reference:
  microsatellites:   # design/microsatellites.bed
  sequences:    # genome/hg38.fa
