classifier:
  locus:
    count:
    # Parameters to set lengths distribution calculation. Take care to keep the
    # same configuration between lean and tag.
      keep_duplicates: true
      # MANDATORY: yes
      # DESCRIPTION: With "true" reads mark as duplicates are counted in lengths
      # distribution.
      padding: 2
      # MANDATORY: yes
      # DESCRIPTION: Number of aligned nucleotids on both sides of a
      # microsatellite locus to use the read in the length distribution
      # calculation. To take a read into account, the process must ensure that
      # it contains the entire repeat. 
      stitch: false
      # MANDATORY: yes
      # DESCRIPTION: With "true" only the reads where the pair is consistent on
      # the repeat length are taken into account.
    min_support: 70
    # MANDATORY: yes
    # DESCRIPTION: For each sample only loci with at least this count of
    # reads/fragments (see stitch) in distribution lengths are keep in model.
    msings:
    # Parameters to set mSINGS classifier
      peak_height_cutoff: 0.05
      # MANDATORY: yes
      # DESCRIPTION: Minimum height to consider a peak in lengths distribution
      # as rate of the highest peak.
input:
  aln_pattern:  # aln/{sample}.bam
  # MANDATORY: yes if R[12]_pattern is missing (start from BAM)
  # DESCRIPTION: Paths pattern to mark duplicates alignments in BAM format and
  # with existing BAI.
  excluded_samples: [Undetermined_S0]
  # MANDATORY: no
  # DESCRIPTION: List of samples names (corresponding to {sample} in aln or
  # reads pattern) in input folder but excluded from the analysis (example:
  # [Undetermined_S0]).
  known_status:   # raw/status.tsv
  # MANDATORY: yes
  # DESCRIPTION: Path to file describing status (MSI or MSS or Undetermined) of
  # each analysed locus (columns) for each sample (rows) format TSV. See example
  # test/config/known_status.tsv.
  R1_pattern:   # raw/{sample}_R1.fastq.gz
  # MANDATORY: yes if aln_pattern is missing (start from FastQ)
  # DESCRIPTION: Paths pattern to R1 files in FastQ format.
  R2_pattern:   # raw/{sample}_R2.fastq.gz
  # MANDATORY: yes if aln_pattern is missing (start from FastQ)
  # DESCRIPTION: Paths pattern to R2 files in FastQ format.
reference:
  microsatellites:   # design/microsatellites.bed
  # MANDATORY: yes
  # DESCRIPTION: Path to the file containing locations of targeted microsatellites
  # in BED format.
  sequences:   # genome/hg38.fa
  # MANDATORY: yes
  # DESCRIPTION: Path to the genome sequences file in Fasta format and with
  # existing FAI and if start from FastQ with bwa index.
