classifier:
  locus:
  # Parameters for classification at locus level.
    count:
    # Parameters to set lengths distribution calculation. Take care to keep the
    # same configuration between lean and tag.
      keep_duplicates: true
      # MANDATORY: yes
      # DESCRIPTION: With "true" reads mark as duplicates are counted in lengths
      # distribution.
      padding: 2
      # MANDATORY: yes
      # DESCRIPTION: Number of aligned nucleotids on both sides of a
      # microsatellite locus to use the read in the length distribution
      # calculation. To take a read into account, the process must ensure that
      # it contains the entire repeat. 
      stitch: false
      # MANDATORY: yes
      # DESCRIPTION: With "true" only the reads where the pair is consistent on
      # the repeat length are taken into account.
    min_support: 70
    # MANDATORY: yes
    # DESCRIPTION: For each sample only loci with at least this count of
    # reads/fragments (see stitch) in distribution lengths are keep in
    # classification.
    msings:
    # Parameters to set mSINGS classifier
      std_dev_rate: 2.0
      # MANDATORY: yes
      # DESCRIPTION: One locus is tagged as unstable if the number of peaks is
      # upper than models_avg_nb_peaks + std_dev_rate * models_std_dev_nb_peaks.
    sklearn:
    # Parameters to set scikit-learn classifier
      classifier: RandomForest
      # MANDATORY: yes
      # DESCRIPTION: Name of the sklearn classifier used.
      # CHOICES: DecisionTree, KNeighbors, LogisticRegression, RandomForest, SVC
      classifier_params: {"n_estimators": 50}
      # MANDATORY: no
      # DESCRIPTION: By default the classifier is used with these default
      # parameters defined in scikit-learn. If you want change these parameters
      # you use this option to provide them as json string.
  model:  # learn/microsat/microsatModel.json
  # MANDATORY: yes
  # DESCRIPTION: Path to the learning model file generated by MInITI learn on 
  # samples with known status and with same targets and laboratory protocol.
  random_seed: 0
  # MANDATORY: yes
  # DESCRIPTION: Random seed used in tag process. To ensure reproducibility of
  # results make sure you use the same seed between two identical analyses.
  sample:
  # Parameters for classification at sample level. It is based on loci
  # instability rate.
    instability_threshold: 0.33
    # MANDATORY: yes
    # DESCRIPTION: With nb_unstable_loci/(nb_stable_loci + nb_unstable_loci)
    # upper than this value the sample is tagged as unstable. Otherwise, it will
    # be stable. 
    locus_weight_is_score: false
    # MANDATORY: yes
    # DESCRIPTION: If "true" the confidence score of each locus is taken into
    # account in sample classification confidence score.
    min_voting_loci: 0.8
    # MANDATORY: yes
    # DESCRIPTION: With (nb_stable_loci + nb_unstable_loci)/nb_all_loci upper
    # than this value the sample status can be tag. Otherwise, it will
    # be undetermined.
    undetermined_weight: 0
    # MANDATORY: yes
    # DESCRIPTION: Weight of undetermined loci in the confidence score on
    # classification.
input:
  aln_pattern:  # aln/{sample}.bam
  # MANDATORY: yes if R[12]_pattern is missing (start from BAM)
  # DESCRIPTION: Paths pattern to mark duplicates alignments in BAM format and
  # with existing BAI.
  excluded_samples: [Undetermined_S0]
  # MANDATORY: no
  # DESCRIPTION: List of samples names (corresponding to {sample} in aln or
  # reads pattern) in input folder but excluded from the analysis (example:
  # [Undetermined_S0]).
  R1_pattern:  # raw/{sample}_R1.fastq.gz
  # MANDATORY: yes if aln_pattern is missing (start from FastQ)
  # DESCRIPTION: Paths pattern to R1 files in FastQ format.
  R2_pattern:  # raw/{sample}_R2.fastq.gz
  # MANDATORY: yes if aln_pattern is missing (start from FastQ)
  # DESCRIPTION: Paths pattern to R2 files in FastQ format.
reference:
  microsatellites:   # design/microsatellites.bed
  # MANDATORY: yes
  # DESCRIPTION: Path to the file containing locations of targeted microsatellites
  # in BED format.
  sequences:   # genome/hg38.fa
  # MANDATORY: yes
  # DESCRIPTION: Path to the genome sequences file in Fasta format and with
  # existing FAI and if start from FastQ with bwa index.
