include: "bwa_mem.smk"
include: "markDuplicates.smk"
include: "mergeMSIReports.smk"
include: "microsatLenDistrib.smk"
include: "microsatMsingsClassify.smk"
include: "microsatMsisensorproProClassify.smk"
include: "microsatSklearnClassify.smk"
include: "wfReport_tag.smk"
